### ISSUE TITLE
Add method to `Session` that allows changing the API endpoint

### ISSUE THREAD

**Issue by aaroncox** [wharfkit/session#73]
Currently once a Session exists, the `client` property on it is fixed to use whatever API endpoint the readonly `chain` property on the Session has. For applications that want to change API endpoints or allow users to do so, they currently need to recreate the Session.

Additional context from Telegram conversation here: https://t.me/wharfkit/1207

**Comment by shaqk** [comment]
Thats good, also maybe supporting array of endpoints with failover and auto selection based on availability/supported_features/latency
